### PR TITLE
TCS-165 Adding check to ensure datastriping is only enabled on STP

### PR DESCRIPTION
**Pull request by David-Mc-Nally**
Specificing the proctype as the Segmented Tickerplant only

### CODE REVIEW

**Review by THarveyWork — COMMENTED** [review]
Looks Good

**Review by AdownieAQ — APPROVED** [review]
LGTM

**Review by ccrease01 — APPROVED** [review]
Looks good

**Review by jonathonmcmurray — COMMENTED** [review]
This looks fine, but I think the PR title is wrong/misleading (this matters because it becomes the commit message when this gets merged, and it needs to be clear).

I think it's more accurate to say that we're adding a check to ensure that datastriping is only enabled on segmentedtickerplant

**Review by jonathonmcmurray — APPROVED** [review]

**Pull request merged**
